name: Avaliação automática

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Verificar desafio 1 (nome no alunos.md)
        run: |
          linhas=$(wc -l < desafios/01-commit/alunos.md)
          if [ "$linhas" -le 2 ]; then
            echo "❌ Você precisa adicionar seu nome no arquivo alunos.md"
            exit 1
          else
            echo "✅ Nome adicionado corretamente"
          fi

      - name: Verificar desafio 3 (resposta preenchida)
        run: |
          linhas=$(wc -l < desafios/03-pull-request/resposta.md)
          if [ "$linhas" -le 1 ]; then
            echo "❌ Você precisa responder a pergunta no resposta.md"
            exit 1
          else
            echo "✅ Resposta adicionada"
          fi
